### ISSUE TITLE
Installation instructions are confusing

### ISSUE THREAD

**Issue by ShamithaSIlva** [orangehrm/api-sample-app-php#6]
I read the instructions in "README.md" file and for step 2 it says "Change lib>API>HTTPRequest url path to the OS system" . But moving from project root there is a lib folder, then I could not find the "API" folder. So it would be better to specify the instruction in step 2 clearly.

**Comment by ShamithaSIlva** [comment]
Changed the config.php and now working fine. Hence closing the issue

**Comment by mayank-istar** [comment]
config.php requires secret and id. Can I use Id and secret generated by google developer console or Id and secret will be provided by Orange HRM.

**Comment by samanthajayasinghe** [comment]
@mayank-istar  you have to add app in admin->Configure->Register Oauth Client with client-id and secret-id
